export { HomePage } from "./home/home";
export { LoginPage } from "./login/login";
export { RegisterPage } from "./register/register";
export { ResetPage } from "./reset/reset";
export { LandsPage } from "./lands/lands";
export { LandPage } from "./land/land";
export { PortionsPage } from "./portions/portions";
export { ProfilePage } from "./profile/profile";
export { ConfigPage } from "./config/config";
